openapi: 3.0.0

info:
  version: '1.0'
  title: 'iNeedHelp Web API'
  description: 'Web Resources Specification for iNeedHelp'

servers:

externalDocs:
  description: Our Project Documentation
  url: https://git.fe.up.pt/lbaw/lbaw2122/lbaw2153/-/wikis/home

tags:
  - name: 'M01: Authentication'
  - name: 'M02: Questions'
  - name: 'M03: Static Pages'
  - name: 'M04: Administration'
  - name: 'M0x: Awsers'
  - name: 'M0x: Users'

paths:
  /login
    get:
      operationId:
      summary: 
      description: 'Provides the login form. ACCESS: VIS'
      tags:
        - 'M01: Authentication'
      responses:
        '200':
          description: 'OK. Show login UI'

    post:
      operationId:
      summary:
      description: 'Processes login form submission. ACCESS: VIS'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                identifier: # username or email
                  type: string
                password:
                  type: string
              required:
                - identifier
                - password

      response:
        '302':
          description: 'Redirect after processing the login credentials'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful authentication'
                  value: '/users/{id}'
                302Error:
                  description: 'Failed authentication. Redirect to login form.'
                  value: '/login'

  /logout
    post:
      operationId:
      summary:
      description: 'Logout the current authenticated user. ACCESS: USR, ADM'
      tags:
        - 'M01: Authentication'
      responses:

  /register
    get:
      operationId:
      summary:
      description: 'Provides the registration form. ACCESS: VIS'
      tags:
        - 'M01: Authentication'
      responses:
    
    post:
      operationId:
      summary:
      description: 'Processes registration form submission. ACCESS: VIS'
      tags:
        - 'M01: Authentication'
      responses:

  /users/{id}
    get:
      operationId:
      summary:
      description: 'Shows authenticated user profile page. ACCESS: VIS'
      tags:
        - 'M03: Users'
      responses:
  
  /question/{id}
    get:
      operationId:
      summary:
      description: 'Shows question page. ACCESS: VIS'
      tags:
        - 'M02: Questions'
      responses:
    
    post:
      operationId:
      summary:
      description: 'Processes new question comment. ACCESS: USR'
      tags:
        - 'M02: Questions'
      responses:

  /question/new-question/
    get:
      operationId:
      summary:
      description: 'Shows new question form. ACCESS: USR'
      tags:
        - 'M02: Questions'
      responses:

    post:
      operationId:
      summary:
      description: 'Processes the new question form. ACCESS: USR'
      tags:
        - 'M02: Questions'
      responses:

  /answer/{id}
    get:
      operationId:
      summary:
      description: 'Shows answer page ACCESS: VIS'
      tags:
        - 'M0x: Answers'
      responses:
    
    post:
      operationId:
      summary:
      description: 'Processes new awser comment. ACCESS: USR'
      tags:
        - 'M0x: Answers'
      responses:
        
  /answer/new-answer/
    get:
      operationId:
      summary:
      description: 'Shows new answer form. ACCESS: USR'
      tags:
        - 'M0x: Answers'
      responses:
        
    post:
      operationId:
      summary:
      description: 'Processes the new answer form. ACCESS: USR'
      tags:
        - 'M0x: Answers'
      reponses:
      
      
  # M03: Static Pages
  /about
    get:
      operationId:
      summary:
      description: 'Shows answer page ACCESS: VIS'
      tags:
        - 'M03: Static Pages'
      responses:

  /support
    get:
      operationId:
      summary:
      description: 'Shows answer page ACCESS: VIS'
      tags:
        - 'M03: Static Pages'
      responses:

  /authentication
    get:
      operationId:
      summary:
      description: 'Shows the needs authentication to do that page. ACCESS: VIS'
      tags:
        - 'M03: Static Pages'
      responses:
  